config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cards
  resources :collections
  resources :collectors


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    has_many :collections
    has_and_belongs_to_many :categories
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :collector
  has_many :cards
end

app/models/collector.rb
class Collector < ApplicationRecord
    has_many :collections
    has_many :cards, through: :collections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card, notice: 'Card was successfully created.'
    else
      render :new
    end
  end

  def update
    if @card.update(card_params)
      redirect_to @card, notice: 'Card was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_url, notice: 'Card was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :description, :attack_value, :defense_value, :effect)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy!

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :collector_id)
    end
end

app/controllers/collectors_controller.rb
class CollectorsController < ApplicationController
  before_action :set_collector, only: %i[ show edit update destroy ]

  def index
    @collectors = Collector.all
  end

  def show
    @collector = Collector.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collector }
    end
  end

  def show
  end

  # GET /collectors/new
  def new
    @collector = Collector.new
  end

  # GET /collectors/1/edit
  def edit
  end

  def create
    @collector = Collector.new(collector_params)

    respond_to do |format|
      if @collector.save
        format.html { redirect_to collector_url(@collector), notice: "Collector was successfully created." }
        format.json { render :show, status: :created, location: @collector }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collectors/1 or /collectors/1.json
  def update
    respond_to do |format|
      if @collector.update(collector_params)
        format.html { redirect_to collector_url(@collector), notice: "Collector was successfully updated." }
        format.json { render :show, status: :ok, location: @collector }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collectors/1 or /collectors/1.json
  def destroy
    @collector.destroy!

    respond_to do |format|
      format.html { redirect_to collectors_url, notice: "Collector was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collector
      @collector = Collector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collector_params
      params.require(:collector).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/collectors_helper.rb
module CollectorsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p>
    <strong>Name:</strong>
    <%= card.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= card.description %>
  </p>

</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :card_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :card_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <div class="field">
    <%= form.label :attack_value %>
    <%= form.number_field :attack_value, id: :card_attack_value %>
  </div>

  <div class="field">
    <%= form.label :defense_value %>
    <%= form.number_field :defense_value, id: :card_defense_value %>
  </div>

  <div class="field">
    <%= form.label :effect %>
    <%= form.text_area :effect, id: :card_effect %>
  </div>

<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cards</h1>

<div id="cards">
  <% @cards.each do |card| %>
    <%= render card %>
    <p>
      <%= link_to "Show this card", card %>
    </p>
  <% end %>
</div>

<%= link_to "New card", new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>
<p>
  <strong>Attack Value:</strong>
  <%= @card.attack_value %>
</p>

<p>
  <strong>Defense Value:</strong>
  <%= @card.defense_value %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @card.effect %>
</p>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>">
  <p>
    <strong>Name:</strong>
    <%= collection.name %>
  </p>

  <p>
    <strong>Collector:</strong>
    <%= collection.collector_id %>
  </p>

</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :collector_id, style: "display: block" %>
    <%= form.text_field :collector_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collections</h1>

<div id="collections">
  <% @collections.each do |collection| %>
    <%= render collection %>
    <p>
      <%= link_to "Show this collection", collection %>
    </p>
  <% end %>
</div>

<%= link_to "New collection", new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection %>

<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection) %> |
  <%= link_to "Back to collections", collections_path %>

  <%= button_to "Destroy this collection", @collection, method: :delete %>
</div>

app/views/collectors/_collector.html.erb
<div id="<%= dom_id collector %>">
  <p>
    <strong>Name:</strong>
    <%= collector.name %>
  </p>

</div>

app/views/collectors/_form.html.erb
<%= form_with(model: collector) do |form| %>
  <% if collector.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collector.errors.count, "error") %> prohibited this collector from being saved:</h2>

      <ul>
        <% collector.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collectors/edit.html.erb
<h1>Editing collector</h1>

<%= render "form", collector: @collector %>

<br>

<div>
  <%= link_to "Show this collector", @collector %> |
  <%= link_to "Back to collectors", collectors_path %>
</div>

app/views/collectors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collectors</h1>

<div id="collectors">
  <% @collectors.each do |collector| %>
    <%= render collector %>
    <p>
      <%= link_to "Show this collector", collector %>
    </p>
  <% end %>
</div>

<%= link_to "New collector", new_collector_path %>

app/views/collectors/new.html.erb
<h1>New collector</h1>

<%= render "form", collector: @collector %>

<br>

<div>
  <%= link_to "Back to collectors", collectors_path %>
</div>

app/views/collectors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collector %>

<div>
  <%= link_to "Edit this collector", edit_collector_path(@collector) %> |
  <%= link_to "Back to collectors", collectors_path %>

  <%= button_to "Destroy this collector", @collector, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

  <title>MyCardCollection</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
  <div class="container mx-auto px-4">
    <%= yield %>
  </div>
  <nav class="bg-gray-800">
    <div class="container mx-auto px-4">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="text-white font-semibold">
            MyCardCollection
          </div>
        </div>
      </div>
    </div>
  </nav>
</body>
</html>